---
#  - name: Setup HTTPS by Nginx reverse proxy
  - name: Installing Nginx and cetbot
    apt:
      name: "{{ item }}"
      state: latest
    with_items:
          - nginx
          - certbot
          - python-certbot-nginx

  - name: Copy nginx configuration file
    template:
      src: templates/nginx.conf
      dest: /etc/nginx/nginx.conf
      mode: '777'
      owner: root

  - name: Get Let's Encrypt cert
    shell: "{{ item }}"
    with_items:
          - apt-get install certbot -y
          - apt-get install python3-certbot-nginx -y
          - nginx -t && nginx -s reload
          - certbot --nginx -d example.com --non-interactive
